config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  #root to: 'welcome#index'
  root 'products#index'
  get 'products/index'
  get 'products/show'
  get 'products/new'
  get 'products/create'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'


  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :products, only: [:index, :create, :show,:update,:edit]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :price, presence: true, numericality: {:greater_than => 0}
    validates :quantity, presence:true, numericality: {only_float: true}
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/products_controller.rb
module Api

  module V1

   class ProductsController < ApplicationController
     def index
      @products = Product.all
      render json: @products
     end
   end

  end

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #before_action :authenticate_user!
    protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all    

  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end


  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product added!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to edit product!'
      render :new
    end
  end


  def edit
    @product = Product.find(params[:id])
  end


  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = 'Product updated!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to edit product!'
      render :edit
    end
  end



  def destroy
    @product = Product.find(params[:id])
    if @product.delete
      flash[:notice] = 'Product deleted!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to delete this product!'
      render :destroy
    end
  end


  def product_params
    params.require(:product).permit(:name, :price, :quantity, :description)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
    <!---<%= stylesheet_link_tag    'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css' %>-->
    <%= stylesheet_link_tag 'https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css' %> 

  </head>

  <body>
    <div class="container">

      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
         Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>

      <%# <ul class="nav">
          <li class="active"><a href="/products">Products</a></li>
      </ul> %>
      <div class="row">
          <div class="col-md-12"><% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice] %>
              </div>
              <% end %> 
             <!--- <% if notice %>
                <p class="alert alert-success"><%= notice %></p>
              <% end %>
              <% if alert %>
                <p class="alert alert-danger"><%= alert %></p>
              <% end %>-->
              
              <%= yield %>
          </div>
        </div>
    </div>

    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
   <!---<%= javascript_include_tag 'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js' %>-->
    <%= javascript_include_tag 'https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js' %>

  </body>
</html>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<div class="modal-content">
  <%= form_for @product, url: {action: :update} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Edit Product</h4>
      </div>
      <div class="modal-body">
        <p>
          <%= "<div class=\"alert alert-danger\">#{@product.errors.full_messages.first}</div>".html_safe if @product.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">Product Name</label>
              <%= f.text_field :name, :class => "form-control" %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Price</label>
              <%= f.text_field :price, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Quantity</label>
              <%= f.text_field :quantity, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Description</label>
              <%= f.text_area :description, :rows => 5, :class => "form-control" %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'products', action: 'index'}, class: 'btn btn-default'%>
        <%= f.submit 'Update Product', :class => "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h4 class="modal-title">Products</h4>
  </div>
  <div class="modal-body">
    <table id="products" class="display" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Description</th>
        <th>Total</th>
        
        <%# <th>Last Modified</th>
        <th>Date Added</th> %>
        <th>Actions</th>
      </tr>
      </thead>
      <%# <tfoot>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Description</th>
        <th>Last Modified</th>
        <th>Date Added</th>
        <th>Actions</th>
      </tr>
      </tfoot> %>
      <tbody>
       <% running_total = 0 %>
      <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= number_to_currency(product.price) %></td>
            <td><%= product.quantity %></td>
            <td><%= truncate(product.description, :length => 75) %></td>
            <td><%= number_to_currency(product.price * product.quantity )%></td>
            
            <!--<td><%= product.updated_at %></td>
            <td><%= product.created_at %></td>-->
            <td>
              <div class="btn-group">
                <%= link_to 'Show', product_path(product), class: 'btn btn-primary' %>
                <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-success' %>
                <%= link_to 'Delete', product_path(product), method: :delete, class: 'btn btn-danger' %>
              </div>
                <% running_total = running_total +(product.price * product.quantity ) %>
            </td>
          
          </tr>
      <% end %>
      </tbody>
    </table>
    <br>

    <div class="btn-group">
        <%= link_to 'Add Product', new_product_path, class: 'btn btn-success' %>
      </div>
    <br>
    <h4 class="pull-right">Product Total:<%= number_to_currency(running_total) %></h4>
  </div>
</div>

app/views/products/new.html.erb
<div class="modal-content">
  <%= form_for Product.new do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Add a Product</h4>
      </div>
      <div class="modal-body">
        <p>
          <%= "<div class=\"alert alert-danger\">#{@product.errors.full_messages.first}</div>".html_safe if @product.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">Product Name</label>
              <%= f.text_field :name, :class => "form-control" %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Price</label>
              <%= f.text_field :price, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Quantity</label>
              <%= f.text_field :quantity, :class => "form-control" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Description</label>
              <%= f.text_field :description, :class => "form-control" %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'products', action: 'index'}, class: 'btn btn-default'%>
        <%= f.submit 'Create Product', :class => "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Show a Product</h4>
      </div>
      <div class="modal-body">
        <p>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">Product Name</label>
              <%= @product.name %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Price</label>
              <%= @product.price %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Quantity</label>
              <%= @product.quantity %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Description</label>
              <%= @product.description %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'products', action: 'index'}, class: 'btn btn-default'%>
      </div>
</div>

app/views/products/update.html.erb
<div class="modal-content">
  <%= form_for @product, url: {action: :update} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Update Product</h4>
      </div>
      <div class="modal-body">
        <p>
          <%= "<div class=\"alert alert-danger\">#{@product.errors.full_messages.first}</div>".html_safe if @product.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">Product Name</label>
              <%= f.text_field :name, :class => "form-control" %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Price</label>
              <%= f.text_field :price, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Quantity</label>
              <%= f.text_field :quantity, :class => "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Description</label>
              <%= f.text_area :description, :rows => 5, :class => "form-control" %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'products', action: 'index'}, class: 'btn btn-default'%>
        <%= f.submit 'Update Product', :class => "btn btn-primary" %>
      </div>
  <% end %>
</div>